name: Build and Publish to Registry on Github push

env:
  GITHUB_SHA: ${{ github.sha }}
  REGISTRY_HOSTNAME: docker.io
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}

on: 
  - push
  - workflow_dispatch

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker Login
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USER --password-stdin

      # Build the Docker image
      - name: Build
        run: |
          export DOCKER_TAG="${REPOSITORY}/hs_docker_base:${GITHUB_SHA}"
          docker build -t $DOCKER_TAG .

      - name: Push Docker Image
        run: |
          docker push $DOCKER_TAG
